// Reads .env and writes utils/config.js so the extension can import the API key.
// Run once before loading the extension: node build-config.js
//
// utils/config.js is git-ignored — never commit it.

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

function parseEnv(text) {
  const result = {};
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    result[key] = val;
  }
  return result;
}

const envPath = resolve(__dirname, '.env');
let env = {};
try {
  env = parseEnv(readFileSync(envPath, 'utf8'));
} catch {
  console.warn('No .env file found — writing empty config.');
}

const apiKey = env.GOOGLE_AI_API_KEY || '';

const output = `// Auto-generated by build-config.js — do NOT commit this file.
export const GOOGLE_AI_API_KEY = ${JSON.stringify(apiKey)};
`;

const outPath = resolve(__dirname, 'utils', 'config.js');
writeFileSync(outPath, output, 'utf8');
console.log(`✓ Wrote utils/config.js (key length: ${apiKey.length})`);
