// Google AI Studio API wrapper — used from background service worker only
// Targets the Gemma 4 31B model (gemma-4-31b-it) via generativelanguage.googleapis.com

const GOOGLE_AI_BASE = 'https://generativelanguage.googleapis.com/v1beta';

// Falls back to the build-time key from utils/config.js (generated by build-config.js).
// At runtime the key stored in the user's profile always takes precedence.
let _builtInKey = '';
try {
  const { GOOGLE_AI_API_KEY } = await import('./config.js');
  _builtInKey = GOOGLE_AI_API_KEY || '';
  console.log('[google-ai] config.js loaded, builtInKey length:', _builtInKey.length);
} catch (e) {
  console.warn('[google-ai] config.js not found or failed to load:', e.message);
}

function resolveKey(apiKey) {
  const resolved = apiKey || _builtInKey;
  console.log('[google-ai] resolveKey — param length:', apiKey?.length ?? 'undefined', '→ resolved length:', resolved.length);
  return resolved;
}

// ── Rate limiter — 15 requests / 60 s ────────────────────────────────────────
// Tracks timestamps of recent calls; if the window is full, waits until the
// oldest call is > 60 s old before allowing the next one through.

const RATE_LIMIT = 15;
const RATE_WINDOW_MS = 60_000;
const _callTimestamps = [];

async function rateLimitedFetch(url, init) {
  const now = Date.now();

  // Drop timestamps older than the window
  while (_callTimestamps.length && now - _callTimestamps[0] >= RATE_WINDOW_MS) {
    _callTimestamps.shift();
  }

  if (_callTimestamps.length >= RATE_LIMIT) {
    // Wait until the oldest slot expires
    const waitMs = RATE_WINDOW_MS - (now - _callTimestamps[0]) + 50; // +50 ms buffer
    await new Promise(r => setTimeout(r, waitMs));
    // Re-prune after waiting
    const t = Date.now();
    while (_callTimestamps.length && t - _callTimestamps[0] >= RATE_WINDOW_MS) {
      _callTimestamps.shift();
    }
  }

  _callTimestamps.push(Date.now());
  return fetch(url, init);
}

// ── Core generate (non-streaming) ────────────────────────────────────────────

export async function googleAIGenerateFull({ apiKey, model, prompt, systemPrompt, temperature = 0.3, timeoutMs = 120000 }) {
  const url = `${GOOGLE_AI_BASE}/models/${model}:generateContent?key=${resolveKey(apiKey)}`;

  const body = {
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    generationConfig: { temperature },
  };
  if (systemPrompt) {
    body.system_instruction = { parts: [{ text: systemPrompt }] };
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await rateLimitedFetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (!response.ok) {
      let detail = '';
      try { const e = await response.json(); detail = e.error?.message || JSON.stringify(e); } catch {}
      throw new Error(`Google AI HTTP ${response.status}${detail ? ': ' + detail : ''}`);
    }

    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text || '';
  } catch (err) {
    clearTimeout(timeout);
    if (err.name === 'AbortError') throw new Error(`Google AI request timed out after ${timeoutMs / 1000}s`);
    throw err;
  }
}

// ── Streaming generate (SSE) ─────────────────────────────────────────────────

export async function googleAIGenerateStream({ apiKey, model, prompt, systemPrompt, onChunk, onDone, temperature = 0.3, timeoutMs = 300000 }) {
  const url = `${GOOGLE_AI_BASE}/models/${model}:streamGenerateContent?alt=sse&key=${resolveKey(apiKey)}`;

  const body = {
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    generationConfig: { temperature },
  };
  if (systemPrompt) {
    body.system_instruction = { parts: [{ text: systemPrompt }] };
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await rateLimitedFetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (!response.ok) {
      let detail = '';
      try { const e = await response.json(); detail = e.error?.message || JSON.stringify(e); } catch {}
      throw new Error(`Google AI HTTP ${response.status}${detail ? ': ' + detail : ''}`);
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let fullText = '';
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop(); // keep last (possibly incomplete) line

      for (const line of lines) {
        if (!line.startsWith('data: ')) continue;
        const jsonStr = line.slice(6).trim();
        if (!jsonStr || jsonStr === '[DONE]') continue;
        try {
          const parsed = JSON.parse(jsonStr);
          const chunk = parsed.candidates?.[0]?.content?.parts?.[0]?.text || '';
          if (chunk) {
            fullText += chunk;
            onChunk?.(chunk, fullText);
          }
        } catch {
          // skip malformed SSE lines
        }
      }
    }

    onDone?.(fullText);
    return fullText;
  } catch (err) {
    clearTimeout(timeout);
    if (err.name === 'AbortError') throw new Error('Google AI stream timed out');
    throw err;
  }
}

// ── Multimodal generate (image + text, for OCR) ──────────────────────────────

export async function googleAIGenerateWithImage({ apiKey, model, prompt, imageBase64, mimeType = 'image/png', temperature = 0, timeoutMs = 120000 }) {
  const url = `${GOOGLE_AI_BASE}/models/${model}:generateContent?key=${resolveKey(apiKey)}`;

  const body = {
    contents: [{ role: 'user', parts: [
      { inline_data: { mime_type: mimeType, data: imageBase64 } },
      { text: prompt },
    ]}],
    generationConfig: { temperature },
  };

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await rateLimitedFetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (!response.ok) {
      let detail = '';
      try { const e = await response.json(); detail = e.error?.message || JSON.stringify(e); } catch {}
      throw new Error(`Google AI HTTP ${response.status}${detail ? ': ' + detail : ''}`);
    }

    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text || '';
  } catch (err) {
    clearTimeout(timeout);
    if (err.name === 'AbortError') throw new Error(`Google AI OCR timed out after ${timeoutMs / 1000}s`);
    throw err;
  }
}

// ── Connection check ─────────────────────────────────────────────────────────
// Validates the API key by listing models (no specific model name required).
// Uses Promise.race as a belt-and-suspenders timeout on top of AbortController.

export async function checkGoogleAIOnline(apiKey, _model) {
  console.log('[google-ai] checkGoogleAIOnline called — apiKey length:', apiKey?.length ?? 'undefined');
  debugger;

  const key = resolveKey(apiKey);
  if (!key) {
    console.warn('[google-ai] No API key available (param + builtIn both empty)');
    return { online: false, error: 'No Google AI API key configured' };
  }

  const url = `${GOOGLE_AI_BASE}/models?key=${key}&pageSize=1`;
  console.log('[google-ai] Fetching:', url.replace(key, key.slice(0, 6) + '…'));

  const TIMEOUT_MS = 8000;

  const timeoutPromise = new Promise(resolve => {
    setTimeout(() => {
      console.warn('[google-ai] checkGoogleAIOnline — hard timeout fired after', TIMEOUT_MS, 'ms');
      resolve({ online: false, error: 'Google AI did not respond within 8s' });
    }, TIMEOUT_MS);
  });

  const fetchPromise = (async () => {
    try {
      const controller = new AbortController();
      const timer = setTimeout(() => {
        console.warn('[google-ai] AbortController.abort() fired');
        controller.abort();
      }, TIMEOUT_MS);

      console.log('[google-ai] fetch starting…');
      const response = await fetch(url, { signal: controller.signal });
      clearTimeout(timer);
      console.log('[google-ai] fetch resolved — status:', response.status);

      if (response.ok) return { online: true, error: null };
      if (response.status === 403 || response.status === 401) {
        return { online: false, error: 'Invalid API key — check your Google AI Studio key' };
      }
      let detail = '';
      try { const e = await response.json(); detail = e.error?.message || ''; } catch {}
      return { online: false, error: `Google AI returned HTTP ${response.status}${detail ? ': ' + detail : ''}` };
    } catch (e) {
      console.error('[google-ai] fetch threw:', e.name, e.message);
      if (e.name === 'AbortError') return { online: false, error: 'Google AI did not respond within 8s' };
      return { online: false, error: `Cannot reach Google AI: ${e.message}` };
    }
  })();

  const result = await Promise.race([fetchPromise, timeoutPromise]);
  console.log('[google-ai] checkGoogleAIOnline result:', result);
  return result;
}

// ── Re-export prompt builders (shared with ollama.js) ───────────────────────

export {
  buildJobDetectionPrompt,
  buildRoleExtractionPrompt,
  buildCommentPrompt,
  buildEmailPrompt,
  buildConnectionRequestPrompt,
} from './ollama.js';
